Employee_Management_System/Employee_Management_System/Models/Project.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Employee_Management_System.Models
{
    public class Project
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ProjectId { get; set; }
        [Required]
        public string ProjectName { get; set; }
    }
}

Employee_Management_System/Employee_Management_System/Controllers/AdminController.cs
using Employee_Management_System.Data;
using Employee_Management_System.Models;
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;

namespace Employee_Management_System.Controllers
{
    public class AdminController : Controller
    {
        private readonly AppDbContext _context;
        public AdminController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<Employee> objCatlist = _context.Employees;
            return View(objCatlist);
        }

        public IActionResult Create()
        {
         
            List<Role> RoleDD = new List<Role>();
            RoleDD = (from c in _context.Roles select c).ToList();
            RoleDD.Insert(0, new Role { RoleId = 0, RoleName = "---Select Role---" });
            ViewBag.msg = RoleDD;
            return View();
        }

        [HttpPost]
        public IActionResult Create(Employee empobj)
        {
            var get_user = _context.Employees.FirstOrDefault(email => email.EmpEmail == empobj.EmpEmail);
            //HttpContext.Session.SetString("FirstName", get_user.EmpFirstName.ToString());
            if (get_user == null)
            {
                _context.Employees.Add(empobj);
                _context.SaveChanges();
                TempData["ResultOk"] = "Registered Successfully!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["ResultOk"] = "Employee allready exist!";
            }

            return View(empobj);
        }

        public IActionResult Edit(int? id)
        {

            List<Role> RoleDD = new List<Role>();
            RoleDD = (from c in _context.Roles select c).ToList();
            RoleDD.Insert(0, new Role { RoleId = 0, RoleName = "---Select Role---" });
            ViewBag.msg = RoleDD;

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var empfromdb = _context.Employees.Find(id);

            if (empfromdb == null)
            {
                return NotFound();
            }
            return View(empfromdb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Employee employee)
        {
            var empfromdb = _context.Employees.Find(id);
            if (empfromdb == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid==false)
            {
                empfromdb.EmpFirstName =employee.EmpFirstName;
                empfromdb.EmpLastName =employee.EmpLastName;
                empfromdb.EmpEmail=employee.EmpEmail;
                empfromdb.EmpAddress=employee.EmpAddress;
                empfromdb.EmpPhoneNumber=employee.EmpPhoneNumber;
                empfromdb.RoleId=employee.RoleId;
                empfromdb.EmpRegisteredDate=employee.EmpRegisteredDate;
                _context.Employees.Update(empfromdb);
                _context.SaveChanges();
                TempData["ResultOk"] = "Data Updated Successfully !";
                return RedirectToAction("Index");
            }

            return View(employee);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var empfromdb = _context.Employees.Find(id);

            if (empfromdb == null)
            {
                return NotFound();
            }
            return View(empfromdb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteEmp(int EmpId)
        {
            var deleterecord = _context.Employees.Find(EmpId);
            if (deleterecord == null)
            {
                return NotFound();
            }
            _context.Employees.Remove(deleterecord);
            _context.SaveChanges();
            TempData["ResultOk"] = "Data Deleted Successfully !";
            return RedirectToAction("Index");
        }

        public IActionResult Dashboard()
        {

            if (HttpContext.Session.GetString("Email") != null)
            {
                return View();

            }
            else
            {
                return RedirectToAction("Login","Employee");
            }
        }


    }
}

Employee_Management_System/Employee_Management_System/Controllers/MapController.cs
using Employee_Management_System.Data;
using Employee_Management_System.Models;
using Microsoft.AspNetCore.Mvc;

namespace Employee_Management_System.Controllers
{
    public class MapController : Controller
    {
        private readonly AppDbContext _context;
        public MapController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Employee> employee = _context.Employees.ToList();
            List<Project> project = _context.Projects.ToList();
            List<Map> map = _context.Maps.ToList();
            var objCatlist = from m in map
                              join e in employee on m.EmpId equals e.EmpId into table1
                              from e in table1.ToList()
                              join p in project on m.ProjectId equals p.ProjectId into table2
                              from p in table2.ToList()
                              select new UiModel
                              {
                                  Mapui = m,
                                  EmployeeUi = e,
                                  ProjectUi = p
                              };
            //List <Map> map =  new List<Map>();
            //var get_user = objCatlist.Single(p => p.ProjectId == map.Any(m=>m.ProjectId)
            //           && p.Password == empobj.EmpPassword);

            return View(objCatlist);
        }

        public IActionResult Create()
        {
            List<Employee> EmpDD = new List<Employee>();
            List<Project> ProjectDD = new List<Project>();
            EmpDD = (from e in _context.Employees select e).ToList();
            ProjectDD = (from c in _context.Projects select c).ToList();
            EmpDD.Insert(0, new Employee{ EmpId = 0, EmpEmail = "---Select Employee---" });
            ProjectDD.Insert(0, new Project{ ProjectId = 0, ProjectName = "---Select Project---" });
            ViewBag.empDropDown = EmpDD;
            ViewBag.projectDropDown = ProjectDD;
            return View();
        }

        [HttpPost]
        public IActionResult Create(Map mapobj)
        {
            try
            {
                var get_user = _context.Maps.FirstOrDefault(Id => Id.EmpId == mapobj.EmpId && Id.ProjectId == mapobj.ProjectId);
                ////HttpContext.Session.SetString("FirstName", get_user.EmpFirstName.ToString());
                if (get_user == null)
                {
                    _context.Maps.Add(mapobj);
                    _context.SaveChanges();
                    TempData["ResultOk"] = "Maped Successfully!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ResultOk"] = "Employee to this project allready exist!";
                }

            }
            catch
            {
                TempData["ResultOk"] = "Employee to this project allready exist!";
            }


            return View(mapobj);
        }

        public IActionResult Edit(int? id)
        {

            List<Employee> EmpDD = new List<Employee>();
            List<Project> ProjectDD = new List<Project>();
            EmpDD = (from e in _context.Employees select e).ToList();
            ProjectDD = (from c in _context.Projects select c).ToList();
            EmpDD.Insert(0, new Employee { EmpId = 0, EmpEmail = "---Select Employee---" });
            ProjectDD.Insert(0, new Project { ProjectId = 0, ProjectName = "---Select Project---" });
            ViewBag.empDropDown = EmpDD;
            ViewBag.projectDropDown = ProjectDD;

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var mapfromdb = _context.Maps.Find(id);

            if (mapfromdb == null)
            {
                return NotFound();
            }
            return View(mapfromdb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Map map)
        {
            var mapfromdb = _context.Maps.Find(id);
            if (mapfromdb == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid == false)
            {
                mapfromdb.EmpId = map.EmpId;
                mapfromdb.ProjectId = map.ProjectId;
                _context.Maps.Update(mapfromdb);
                _context.SaveChanges();
                TempData["ResultOk"] = "Data Updated Successfully !";
                return RedirectToAction("Index");
            }

            return View(map);
        }


        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var mapfromdb = _context.Maps.Find(id);

            if (mapfromdb == null)
            {
                return NotFound();
            }
            return View(mapfromdb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteMap(int MapId)
        {
            var deleterecord = _context.Maps.Find(MapId);
            if (deleterecord == null)
            {
                return NotFound();
            }
            _context.Maps.Remove(deleterecord);
            _context.SaveChanges();
            TempData["ResultOk"] = "Data Deleted Successfully !";
            return RedirectToAction("Index");
        }

        public IActionResult Dashboard()
        {

            if (HttpContext.Session.GetString("Email") != null)
            {
                return View();

            }
            else
            {
                return RedirectToAction("Login", "Employee");
            }
        }

    }
}

Employee_Management_System/Employee_Management_System/Controllers/ProjectController.cs
using Employee_Management_System.Data;
using Employee_Management_System.Models;
using Microsoft.AspNetCore.Mvc;

namespace Employee_Management_System.Controllers
{
    public class ProjectController : Controller
    {
        private readonly AppDbContext _context;
        public ProjectController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<Project> objCatlist = _context.Projects;
            return View(objCatlist);
        }

        public IActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Create(Project projectobj)
        {
            var get_project = _context.Projects.FirstOrDefault(id => id.ProjectId == projectobj.ProjectId);
            if (get_project == null)
            {
                _context.Projects.Add(projectobj);
                _context.SaveChanges();
                TempData["ResultOk"] = "Project Registered Successfully!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["ResultOk"] = "Project allready exist!";
            }

            return View(projectobj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var projectfromdb = _context.Projects.Find(id);

            if (projectfromdb == null)
            {
                return NotFound();
            }
            return View(projectfromdb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id,Project project)
        {
            var projectfromdb = _context.Projects.Find(id);
            if (projectfromdb == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                projectfromdb.ProjectName = project.ProjectName;
                _context.Projects.Update(projectfromdb);
                _context.SaveChanges();
                TempData["ResultOk"] = "Data Updated Successfully !";
                return RedirectToAction("Index");
            }

            return View(project);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var projectfromdb = _context.Projects.FirstOrDefault(m => m.ProjectId == id);

            if (projectfromdb == null)
            {
                return NotFound();
            }
            return View(projectfromdb);
        }

        [HttpPost]
        public IActionResult DeleteProject(int ProjectId)
        {
            var projectfromdb = _context.Projects.FirstOrDefault(m => m.ProjectId == ProjectId);
            _context.Projects.Remove(projectfromdb);
            _context.SaveChanges();
            TempData["ResultOk"] = "Data Deleted Successfully !";
            return RedirectToAction("Index");
        }

        public IActionResult Dashboard()
        {
            if (HttpContext.Session.GetString("Email") != null)
            {
                return View();

            }
            else
            {
                return RedirectToAction("Login", "Employee");
            }
        }

    }
}

Employee_Management_System/Employee_Management_System/Views/Project/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Project

@section TopMenu {
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Dashboard">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Project List</a>
        </li>  
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Map List</a>
        </li>
    </ul>
}
    <div class="container shadow p-5">
        <div class="row pb-2">
            <h2>Add Project</h2>
        </div>

        <form method="post">
            <div asp-validation-summary="All"></div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="ProjectName">Project Name</label>
                    <input type="text" class="form-control mb-3" asp-for="ProjectName" placeholder="Enter Project Name">
                    <span asp-validation-for="ProjectName" class=" alert-danger"></span>
                </div>
                </div>
            <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Save</button>
            <a asp-controller="Project" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To List</a>
        </form>

    </div>


    @*//for front end validations*@

    @section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

Employee_Management_System/Employee_Management_System/Views/Project/Dashboard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model Employee
@{
    ViewBag.Title = "DashBoard";
}
@section TopMenu {
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Dashboard">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Project List</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Map List</a>
        </li>
    </ul>
}
@if (@Context.Session.GetString("FirstName") != null)
{

    <div style=" color:red; font:900">
        <h1>Hello, @Context.Session.GetString("FirstName").ToString()</h1>
    </div>

}
<div class="container shadow p-5">

    <h1 class="text-center mb-3">Your Info</h1>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
             @*   <th scope="col">Id</th>*@
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">Address</th>
                <th scope="col">Phone Number</th>
               @* <th scope="col">Role ID</th>*@
                <th scope="col">Role Name</th>
                <th scope="col">Registration Date</th>

              @*  <th></th>*@
            </tr>
        </thead>
        <tbody>
                <tr>
                    <td width="20%">
                    @Context.Session.GetString("FirstName").ToString()
                    </td>
                    <td width="20%">
                    @Context.Session.GetString("LastName").ToString()
                    </td>
                    <td width="20%">
                    @Context.Session.GetString("Email").ToString()
                    </td>
                    <td width="25%">
                    @Context.Session.GetString("Address").ToString()
                    </td>
                    <td width="25%">
                    @Context.Session.GetString("Phone").ToString()
                    </td>
                    @*<td width="25%">
                    @Context.Session.GetString("RoleId").ToString()
                    </td>*@
                <td width="25%">
                    @Context.Session.GetString("RoleName").ToString()
                </td>
                <td width="25%">
                    @Context.Session.GetString("Date").ToString()
                    </td>
                 
                   
                </tr>
            
        </tbody>
    </table>
</div>

Employee_Management_System/Employee_Management_System/Views/Project/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Project
@section TopMenu {
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Dashboard">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Project List</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Map List</a>
        </li>
    </ul>
}
<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Delete Project</h2>
    </div>

    <form method="post" asp-action="DeleteProject">
        <input asp-for="ProjectId" hidden />
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="ProjectName">Project Name</label>
                <input type="text" class="form-control mb-3" asp-for="ProjectName" disabled>
                <span asp-validation-for="ProjectName" class=" alert-danger"></span>
            </div>
         </div>
        <button type="submit" class="btn btn-lg btn-danger p-2"><i class="bi bi-trash-fill"></i>Delete</button>
        <a asp-controller="Project" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To List</a>
    </form>

</div>


@*//for front end validations*@

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    }

Employee_Management_System/Employee_Management_System/Views/Project/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Project
@section TopMenu {
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Dashboard">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Project List</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Map List</a>
        </li>
    </ul>
}
<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Edit Project</h2>
    </div>

    <form method="post" asp-action="Edit">
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="ProjectName">Project Name</label>
                <input type="text" class="form-control mb-3" asp-for="ProjectName">
                <span asp-validation-for="ProjectName" class=" alert-danger"></span>
            </div>
</div>

        <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Update</button>
        <a asp-controller="Project" asp-action="Index" class="btn btn-lg btn-warning p-2">Back To List</a>
    </form>

</div>


@*//for front end validations*@

@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

Employee_Management_System/Employee_Management_System/Views/Project/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Project>
@section TopMenu {
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Dashboard">Profile</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Project List</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Map List</a>
        </li>
    </ul>
}
    @{
    ViewData["Title"] = "Index";
}

@if (TempData["ResultOk"] != null)
{
    <h1 class="alert-success">@TempData["ResultOk"]</h1>
}

<div class="container shadow p-5">

    <h1 class="text-center mb-3">Project List</h1>

    <div class="col mb-3">
        <a asp-controller="Project" asp-action="Create" class="btn btn-lg btn-primary"><i class="bi bi-file-plus-fill"></i>Add Project</a>
    </div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
          @*      <th scope="col">Id</th>*@
                <th scope="col">Project Name</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                   @* <td width="20%">
                        @item.ProjectId
                    </td>*@
                    <td width="20%">
                        @item.ProjectName
                    </td>
                    <td>
                        <div role="group" class="w-60 btn-group">
                            <a asp-controller="Project" asp-action="Edit" asp-route-id="@item.ProjectId" class=" btn btn-sm btn-primary"><i class="bi bi-pencil-square"></i>Edit</a>&nbsp;
                            <a asp-controller="Project" asp-action="Delete" asp-route-id="@item.ProjectId" class="btn btn-sm btn-danger"><i class="bi bi-trash-fill"></i>Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>